### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by alexandru-dinu** [alexandru-dinu/simple-zsh#1]
- [x] initialization
  - [x] `fpath` (also for plugins)
  - [x] completion dump / cache (`.zcompdump`)
  - see https://github.com/ohmyzsh/ohmyzsh/blob/master/oh-my-zsh.sh 

- [x] completion
  - see https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/completion.zsh
  - [x] case-insensitive completion
  - [x] completion menu on successive tab press
  
- [x] everything should reside under `~/.zsh/`

- [x] plugin array: `plugins=(x y z)` as in oh-my-zsh
  - each plugin should be sourced from `plugins/x/x.plugin.zsh` 

- [x] history timestamps
  - see https://github.com/ohmyzsh/ohmyzsh/blob/master/lib/history.zsh

- [x] simple prompt 
  - see [pure](https://github.com/sindresorhus/pure)
  - helper functions should return vanilla text, theming will be done separately 
  - [x] git: current branch, dirty
  - [x] conda env
  - [x] return status

- [x] working `.zshrc` template
  - will finally source a main "entry-point" (e.g. `source $ZSH/oh-my-zsh.sh`) 

- [x] `nocorrect` aliases for certain commands

- [x] github actions (macos and linux)
  - [x] syntax
  - [x] installation
 
- optional
  - completion waiting dots

**Comment by alexandru-dinu** [comment]
Looks good for the first version!
Using at as main shell since alexandru-dinu/gizmos@57fae48439b96823e4a54c642335671da0270f5d.
